1.0.3 - Bug Fix Attempt to fix the error where target equals null on execution of PhantomListener. This should work!
```- [Thu 17:32:01 ERROR Minecraft] Could not pass event EntityTargetLivingEntityEvent to Phantom-Repellent v1.0.2-Paper_Release
   java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getPersistentDataContainer()" because "target" is null
       at phantom-repellent-1.0.2-Paper_Release.jar//me.lynxid.phantomRepellent.listeners.PhantomListener.onEntityTarget(PhantomListener.java:27)```